# Generated by Django 5.1.7 on 2025-03-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0003_alter_block_user'),
    ]

    operations = [
    ]
