# Generated by Django 5.1.7 on 2025-03-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0004_auto_20250321_1053'),
    ]

    operations = [
    ]
